version: '3'

services:
  postgres:
    image: 'postgres:12.11'
    ports:
      - "5480:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: sdd
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./db/postgres.sql:/docker-entrypoint-initdb.d/postgres.sql
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: budget_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
